"""Add Cloudinary public ID to car images

Revision ID: 00cfddfc8924
Revises: 
Create Date: 2026-08-31 16:33:28.053211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00cfddfc8924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_images', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
